---
#############################################################################
# Copyright 2018 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

- name: handler_start_aria2c
  systemd:
    name: "aria2c.service"
    daemon_reload: "yes"
    state: "started"

- name: handler_stop_aria2c
  systemd:
    name: "aria2c.service"
    daemon_reload: "yes"
    state: "stopped"

- name: handler_restart_aria2c
  systemd:
    name: "aria2c.service"
    daemon_reload: "yes"
    state: "restarted"

- name: handler_enable_aria2c
  systemd:
    name: "aria2c.service"
    daemon_reload: "yes"
    enabled: "yes"

- name: handler_disable_aria2c
  systemd:
    name: "aria2c.service"
    daemon_reload: "yes"
    enabled: "no"
